### ISSUE TITLE
Cannot close a closed AudioContext.

### ISSUE THREAD

**Issue by Jj-614** [ocavue/vad-web#15]
<template>
  <div id="app">
    <nav>
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link>
      <button @click="han">点我</button>
      <button @click="re">点我re</button>
    </nav>
    <router-view />
  </div>
</template>
<script>
import { startRecording } from 'vad-web';

const audioWorkletURL = '/vad-audio-worklet.js';
export default {
  name: 'App',
  methods: {
    re() {
      console.log('refersh---Recording');
      if (this.dispose) {
        this.dispose();
        this.dispose = null;
      }
   
      this.dispose = startRecording({
        // The URL of the audio worklet script. More on this below.
        audioWorkletURL,

        // The maximum duration of `audioData` received by `onAudioData`.
        maxDurationSeconds: 30,

        // Called when audio data is received.
        onAudioData: (audioData, sampleRate) => {
          console.log(` samples @ ${sampleRate}Hz`);
        },

        // Called when silence is detected.
        onSilence: () => {
          console.log('Silence detected');
        },

        // Called when speech is detected.
        onSpeech: () => {
          console.log('Speech detected');
        },
      });
    },
    han() {
      if (this.dispose) {
        this.dispose();
        this.dispose = null;
      }
    },
  },
  mounted() {
    this.re();
  },
  components: {},
};
</script>
<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

nav {
  padding: 30px;
}

nav a {
  font-weight: bold;
  color: #2c3e50;
}

nav a.router-link-exact-active {
  color: #42b983;
}
</style>
![test](https://github.com/user-attachments/assets/577dd673-a39f-45e8-8463-65a272f42229)

When I triggered the re event for many times, the error occurred. What is the cause?@

**Comment by Jj-614** [comment]
@ocavue

**Comment by Jj-614** [comment]
Please have a look at it sometime. Thank you

**Comment by Jj-614** [comment]
An error causes multiple Vads to be created
![222](https://github.com/user-attachments/assets/d2433af5-0aa4-4634-92ad-6f0d63fb660b)

**Comment by ocavue** [comment]
Please provide a runnable repository to reproduce your errors. I cannot debug it with just your code snippet. You can start it with https://github.com/ocavue/vad-web/tree/master/examples/with-vite

**Comment by Jj-614** [comment]
git@github.com:xiaoBing5102/vad-test.git        ssh password 123456    After npm i is required, use npm run serve to start
Quickly click the button in the picture to reappear the problem
![222](https://github.com/user-attachments/assets/02b11a4b-ba35-4d79-9c35-628f4623765c)

**Comment by ocavue** [comment]
The browser needs time to close the previous recording, that's why the dispose function returns a promise. You need to wait for the previous dispose function to stop first, before starting a new recording. Adding `await` should fix the issue. 

```diff
+   async re() {
-   re() {
      console.log('refersh---Recording');
      if (this.dispose!==null) {
+       await this.dispose();
-       this.dispose();
        this.dispose = null;
      }
   
      this.dispose = startRecording({
        // ... 
      });
    },

  },
```

**Comment by ocavue** [comment]
Could you try if this fixes the error on your side?

**Comment by Jj-614** [comment]
I tried, but it didn't work. Thank you
---- Replied Message ----
From ***@***.***> Date 12/19/2024 11:20 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [ocavue/vad-web] Cannot close a closed AudioContext. (Issue #15) 
Could you try if this fixes the error on your side?

**Comment by Jj-614** [comment]
I think the sequence of destruction was out of order because onSpeech triggered it two or more times
---- Replied Message ----
From ***@***.***> Date 12/19/2024 11:20 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [ocavue/vad-web] Cannot close a closed AudioContext. (Issue #15) 
Could you try if this fixes the error on your side?

**Comment by ocavue** [comment]
Could you update `vad-web` to the latest v0.4.0 and try the following code?



```diff
+   async re() {
-   re() {
      console.log('refersh---Recording');
      if (this.dispose!==null) {
+       await this.dispose();
-       this.dispose();
        this.dispose = null;
      }
   
+     this.dispose = await startRecording({
-     this.dispose = startRecording({
        // ... 
      });
    },

  },
```

**Comment by Jj-614** [comment]
There is no error in version 0.4, but onspeech is still activated two or more times
---- Replied Message ----
From ***@***.***> Date 12/19/2024 12:02 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [ocavue/vad-web] Cannot close a closed AudioContext. (Issue #15) 
Could you update vad-web to the latest v0.4.0 and try the following code?
+ async re() { - re() { console.log('refersh---Recording'); if (this.dispose!==null) { + await this.dispose(); - this.dispose(); this.dispose = null; } + this.dispose = await startRecording({ - this.dispose = startRecording({ // ... }); }, },

**Comment by ocavue** [comment]
Please try the latest v0.4.1. Notice that you need to copy the [vad-audio-worklet.js](https://unpkg.com/vad-web/dist/vad-audio-worklet.js) file every time you update this package.

**Comment by Jj-614** [comment]
0.4.1 Should have been fixed, there is currently no reappearing worship of the Boss
---- Replied Message ----
From ***@***.***> Date 12/19/2024 16:31 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [ocavue/vad-web] Cannot close a closed AudioContext. (Issue #15) 
Please try the latest v0.4.1. Notice that you need to copy the vad-audio-worklet.js file every time you update this package.
