### ISSUE TITLE
Uncaught (in promise) Error: Failed to initialize recording: AbortError: Unable to load a worklet's module.

### ISSUE THREAD

**Issue by Jj-614** [ocavue/vad-web#5]
vue 2 Uncaught (in promise) Error: Failed to initialize recording: AbortError: Unable to load a worklet's module.

**Comment by ocavue** [comment]
Please follow the README to config your bundler. You can also provide a minimal reproduction if you need further help.

**Comment by xiaoBing5102** [comment]
![Uploading Snipaste_2024-12-05_19-59-24.png…]()

**Comment by xiaoBing5102** [comment]
![Uploading Snipaste_2024-12-05_19-59-24.png…]()

**Comment by Jj-614** [comment]
![Snipaste_2024-12-05_19-59-33](https://github.com/user-attachments/assets/d5e00dba-7c11-4096-801a-329810741145)

**Comment by Jj-614** [comment]
![Snipaste_2024-12-05_19-59-24](https://github.com/user-attachments/assets/5b3ca337-e62c-4071-9827-0fe0b45a1242)

**Comment by xiaoBing5102** [comment]
我尝试过audioWorkletURL = '/vad-audio-worklet.js'  依旧报错

**Comment by Jj-614** [comment]
I tried audioWorkletURL = '/vad-audio-worklet.js' but still got an error

**Comment by Jj-614** [comment]
![Snipaste_2024-12-05_20-03-55](https://github.com/user-attachments/assets/41b0acb4-b72f-4e33-a2ff-79f451c66538)

**Comment by Jj-614** [comment]
![Snipaste_2024-12-05_20-04-31](https://github.com/user-attachments/assets/e0e63d1b-c1f6-4dcf-9c9e-3f8fb2b2f8d9)
